# # Node.js with Angular
# # Build a Node.js project that uses Angular.
# # Add steps that analyze code, save build artifacts, deploy, and more:
# # https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 branches:
   include:
     - master
     - develop

pool:
  vmImage: ubuntu-latest

stages:
- stage: NodeInstall
  displayName: 'Node install'
  jobs:
    - job: Install
      steps:
      - script: echo installing node.js 
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Install Node.js'

- stage: NpmBuild
  displayName: 'NPM Install'
  dependsOn: NodeInstall
  jobs:
    - job: Build
      steps:
      - script: |
          npm install -g @angular/cli
          npm install
          npm run build:storybook

- stage: CopyFiles
  displayName: 'Copy file using task'
  jobs:
    - job: CopyFiles
      steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/dist/'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/example-component-library'         

- stage: copynpmrc
  displayName: 'Copy npmrc file'
  jobs:
    - job: CopyFiles
      steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '.npmrc'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/example-component-library'
      - script: ls
    

- stage: NpmPublish
  displayName: 'NPM Install'
  jobs:
    - job: authenticate
      steps:
      - task: npmAuthenticate@0
        inputs:
          workingFile: '$(Build.SourcesDirectory)/.npmrc'  # Automatically handles authentication for Azure Artifacts
        displayName: 'Authenticate with Azure Artifacts'    

    - job: publish
      steps: 
      - task: Npm@1
        inputs:
          command: 'publish'
          workingDir: '$(Build.SourcesDirectory)/dist/example-component-library'
          publishRegistry: 'useFeed'
          publishFeed: '4ab01b9f-7e82-421e-9ee3-b8e64e59767f'
          

