# # Node.js with Angular
# # Build a Node.js project that uses Angular.
# # Add steps that analyze code, save build artifacts, deploy, and more:
# # https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 branches:
   include:
     - master
     - develop

pool:
  vmImage: ubuntu-latest

stages:
- stage: NodeInstall
  displayName: 'Node install'
  jobs:
    - job: Install
      steps:
      - script: echo installing node.js 
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Install Node.js'

- stage: NpmBuild
  displayName: 'NPM Install'
  dependsOn: NodeInstall
  jobs:
    - job: Build
      steps:
      - script: |
          npm install -g @angular/cli
          npm install
          npm run build:storybook

- stage: CopyFiles
  displayName: 'Copy file using task'
  jobs:
    - job: CopyFiles
      steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/dist/'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '.npmrc'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/example-component-library'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/example-component-library'
          ArtifactName: 'drop'
          publishLocation: 'Container'      

- stage: Publish
  displayName: publishnpm
  jobs:
      - job:
        displayName: "Publish npm package"
        workspace:
          clean: all
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              source: "current"
              artifact: "drop"
              path: '$(Pipeline.Workspace)/drop'
          - task: npmAuthenticate@0
            inputs:
              workingFile: ".npmrc"
          - task: Npm@1
            inputs:
              command: 'publish'
              workingDir: '$(Pipeline.Workspace)/drop'
              publishRegistry: 'useFeed'
              publishFeed: '4ab01b9f-7e82-421e-9ee3-b8e64e59767f'


# - stage: NpmPublish
#   displayName: 'NPM Install'
#   jobs:
#     - job: authenticate
#       steps:
#       - task: npmAuthenticate@0
#         inputs:
#           workingFile: '$(Build.ArtifactStagingDirectory)/example-component-library.npmrc'  # Automatically handles authentication for Azure Artifacts
#         displayName: 'Authenticate with Azure Artifacts'   

#     - job: publish
#       steps: 
#       - task: Npm@1
#         inputs:
#           command: 'publish'
#           workingDir: '$(Build.SourcesDirectory)/dist/example-component-library'
#           publishRegistry: 'useFeed'
#           publishFeed: '4ab01b9f-7e82-421e-9ee3-b8e64e59767f'
          

