# # Node.js with Angular
# # Build a Node.js project that uses Angular.
# # Add steps that analyze code, save build artifacts, deploy, and more:
# # https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 branches:
   include:
     - master
     - develop
     - feature/*

pool:
  vmImage: ubuntu-latest

stages:
- stage: NodeInstall
  displayName: 'Node install'
  jobs:
    - job: Install
      steps:
      - script: echo installing node.js 
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Install Node.js'

- stage: NpmBuild
  displayName: 'NPM Install'
  dependsOn: NodeInstall
  jobs:
    - job: Build_and_Copy
      steps:
      - script: |
          npm install -g @angular/cli
          npm install
          npm run build:storybook

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/dist/'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/'
          Contents: '.npmrc'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/example-component-library'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/example-component-library'
          ArtifactName: 'drop'
          publishLocation: 'Container'       
        

- stage: NpmPublish
  displayName: 'NPM Install'
  jobs:
    - job: authenticate
      steps:
      - task: npmAuthenticate@0
        inputs:
          workingFile: '$(Pipeline.Workspace)/.npmrc'  # Automatically handles authentication for Azure Artifacts
        displayName: 'Authenticate with Azure Artifacts'    

    - job: publish
      steps: 
      - task: Npm@1
        inputs:
          command: 'publish'
          workingDir: '$(Pipeline.Workspace)/drop'
          publishRegistry: 'useFeed'
          publishFeed: 'd2ab0d77-cb6e-4f93-9132-b62e65eccd45/e4c0301c-90c2-4515-b46e-f74781cac68e'
          

